import express from "express";
import {adminLoginController,adminMeController,adminLogoutController,} from "../Controller/admin.Controller.js";
import { getAdminDashboardController } from "../Controller/adminDashboard.Controller.js";
import { adminLoginValidation } from "../Validation/admin.Validation.js";
import { validate } from "../Middleware/validate.Middleware.js";
import { protectAdmin } from "../Middleware/adminonly.Middleware.js";
import {adminGetAdventuresController,adminCreateAdventureController,adminUpdateAdventureController,adminTrashAdventureController,adminGetAdventureTrashController,adminRestoreAdventureController,adminPermanentDeleteAdventureController,} from "../Controller/adventure.Controller.js";
import {createAdventureValidation,updateAdventureValidation,} from "../Validation/adventure.Validation.js";
import {adminGetQuestionsController,adminCreateQuestionController,adminUpdateQuestionController,adminTrashQuestionController,adminGetQuestionTrashController,adminRestoreQuestionController,adminPermanentDeleteQuestionController,} from "../Controller/question.Controller.js";
import {createQuestionValidation,updateQuestionValidation,} from "../Validation/question.Validation.js";
import {getAdminStudentStatusesController,} from "../Controller/adminStudentStatus.Controller.js";
import {disableStudentController,enableStudentController,} from "../Controller/adminStudentManagement.Controller.js";
import {adminLoginLimiter} from "../Middleware/rateLimit.Middleware.js";

const router = express.Router();
router.post("/login",adminLoginLimiter,validate(adminLoginValidation), adminLoginController);
router.get("/me", protectAdmin, adminMeController);
router.post("/logout", protectAdmin, adminLogoutController);
router.get("/dashboard", protectAdmin, getAdminDashboardController);
router.get("/students/status",protectAdmin,getAdminStudentStatusesController);
router.get("/adventures",protectAdmin,adminGetAdventuresController);
router.post("/adventures",protectAdmin,validate(createAdventureValidation),adminCreateAdventureController);
router.put("/adventures/:id",protectAdmin,validate(updateAdventureValidation),adminUpdateAdventureController);
router.delete("/adventures/:id",protectAdmin,adminTrashAdventureController);
router.get("/trash/adventures",protectAdmin,adminGetAdventureTrashController);
router.patch("/trash/adventures/:id/restore",protectAdmin,adminRestoreAdventureController);
router.delete("/trash/adventures/:id/permanent",protectAdmin,adminPermanentDeleteAdventureController);
router.get("/questions",protectAdmin,adminGetQuestionsController);
router.post("/questions",protectAdmin,validate(createQuestionValidation),adminCreateQuestionController);
router.put("/questions/:id",protectAdmin,validate(updateQuestionValidation),adminUpdateQuestionController);
router.delete("/questions/:id",protectAdmin,adminTrashQuestionController);
router.get("/trash/questions",protectAdmin,adminGetQuestionTrashController);
router.patch("/trash/questions/:id/restore",protectAdmin,adminRestoreQuestionController);
router.delete("/trash/questions/:id/permanent",protectAdmin,adminPermanentDeleteQuestionController);
router.patch("/students/:id/disable",protectAdmin,disableStudentController);
router.patch("/students/:id/enable",protectAdmin,enableStudentController);
export default router;